spring.application.name=spring-boot-core
server.port=8081
my.custom.property=MyCustomValue
feature.enabled=true

app.config.name=ExampleApp
app.config.description=Applicazione di esempio
app.config.max-users=100